### ISSUE TITLE
默认创建用户

### ISSUE THREAD

**Issue by rexren** [rexren/Enterprise-Quality#1]
可以使用sql初始化功能，默认创建用户进去，不然登录会总是失败

**Comment by SherryLang** [comment]
收到，import文件比较复杂，要判断id是否存在，还在研究中

**Comment by rexren** [comment]
import.sql应该是创建表时导入的？如果已经创建这个应不起作用。

**Comment by SherryLang** [comment]
查了spring boot文档 [78.2 Initialize a database using Hibernate](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html)，import.sql只有在建表的时候才会运行：
> a file named **import.sql** in the root of the classpath will be executed on startup if Hibernate creates the schema from scratch (that is if the ddl-auto property is set to **create** or **create-drop**).  It is a Hibernate feature (nothing to do with Spring).
这样必须设置
`spring.jpa.hibernate.ddl-auto = update`
每次运行重新建表。
如果需要在每次程序运行的时候运行sql INSERT语句，则需要使用schema.sql：
> Spring JDBC has a DataSource initializer feature. Spring Boot enables it by default and loads SQL from the standard locations **schema.sql** and **data.sql** (in the root of the classpath). 
我试了一下，如果INSERT语句不指定ID，这个文件的运行是增量式的，只要没有唯一键，每次运行都会执行一个INSERT并且自动生成ID。如果指定ID，INSERT一次之后，ID会重复，程序报错无法启动。
目前制定的策略是先不指定ID，程序启动时自动建立一个访客账户，以免没有账户无法登陆。

**Comment by SherryLang** [comment]
好像可以指定数据库类型，这样可以把dev模式和release模式分开？
